# Generated by Django 4.2.19 on 2025-02-28 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_post_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="user",
        ),
    ]
